# This is a basic workflow to help you get started with Actions

name: Powershell-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.x
      #- run: ls "C:\Windows\Microsoft.NET\Framework64"
      - run: dotnet restore .\MySFWebApp8.sln

      # Runs a set of commands using the runners shell
      - name: Install ServiceFabric Powershell Module
        run: ./installmod.ps1
        
      #- name: Build ServiceFabric Application
      #  run: dotnet build .\MySFWebApp8.sln
      
      #- name: Check VS
      #  run: ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
      
      - name: Build package
        env:  
            OUTPUT_SUFFIX: 	${Env:ProgramFiles(x86)}+"\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MsBuild.exe"
        run: '&$OUTPUT_SUFFIX'
      
      #- name: Check msbuild
      #  run: msbuild
        
