# This is a basic workflow to help you get started with Actions

name: Powershell-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.x
      #- run: ls "C:\Windows\Microsoft.NET\Framework64"
      #- run: dotnet restore .\MySFWebApp8.sln
      
      #- run: ./deploy/build_deploy.ps1

      # Runs a set of commands using the runners shell
      - name: Install ServiceFabric Powershell Module
        run: |
                New-Item .\installer -ItemType Directory
                Invoke-WebRequest "http://download.microsoft.com/download/3/2/1/3217654F-6882-4CEA-BD51-49287EDECE9B/MicrosoftServiceFabricSDK.2.8.232.msi" -OutFile .\installer\ServiceFabricSDK.msi"
                ls .\installer
                #./installmod.ps1
                #Connect-ServiceFabricCluster -ConnectionEndpoint mysfwebapp8.eastus.cloudapp.azure.com:19000 `
                #-KeepAliveIntervalInSec 10 `
                #-X509Credential -ServerCertThumbprint 6B5DA229ED923914B618D3B682EFD82447FC8D5F `
                #-FindType FindByThumbprint -FindValue 6B5DA229ED923914B618D3B682EFD82447FC8D5F `
                #-StoreLocation CurrentUser -StoreName My
        
      #- name: Build ServiceFabric Application
      #  run: dotnet build .\MySFWebApp8.sln
      
      #- name: Check VS
      #  run: ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
      
      #- name: Build package
      #  run: ./deploy/Package.ps1
      
      #- name: Deploy ServiceFabric Application
      #  run: ./deploy/build_deploy.ps1
        
